# Week 3 : NumPy basics and vectorized computation Exercises

In [1]:
import numpy as np


Generate a 3x4 NumPy array with random integers between 1 and 50.

a. Calculate and print the Mean, Median, and Standard Deviation of the array

b. Print the Sum of all elements and the sum of each row.

c. Reshape the 3x4 array into a 2x6 array and print it.


In [12]:
arr = np.random.randint(1, 50, size=(3,4))   # random.randint generates random integers with (start, stop (exclusive), size)
print("The numpy array is : \n",arr)

print("\nThe mean of all numbers in the array is : ", np.mean(arr))    # np.mean gives the mean of all numbers in array
print("\nThe median of all numbers in the array is :", np.median(arr))   # np.median gives the median value of all numbers in array
print("\nThe standard deviation of all numbers in the array is : ", np.std(arr))   # np.std gives the standard deviation value of an array
print("\nThe sum of all numbers in the array is : ", np.sum(arr))    # np.sum gives the sum of all numbers in array
print("\nThe sum of each row is : ", np.sum(arr, axis=1))   # np.sum with axis = 1 gives row sum and axis = 0 gives column sum individually

print("\nThe new array reshaped from 3x4 to 2x6 is : \n", np.reshape(arr, (2,6)))   # np.reshape takes the array and new size and reshapes the array

The numpy array is : 
 [[38 48 32 34]
 [16 43 21 48]
 [15 18  9 15]]

The mean of all numbers in the array is :  28.083333333333332

The median of all numbers in the array is : 26.5

The standard deviation of all numbers in the array is :  13.444071390600227

The sum of all numbers in the array is :  337

The sum of each row is :  [152 128  57]

The new array reshaped from 3x4 to 2x6 is : 
 [[38 48 32 34 16 43]
 [21 48 15 18  9 15]]


Create two (3 * 3) matrices using NumPy and print it. Perform and print the results of the following linear algebra operations

a. Matrix addition

b. Matrix subtraction

c. Matrix multiplication (element-wise and dot product)

d. Transpose of a matrix

e. Determinant and inverse (if applicable)

In [ ]:
arr1 = np.random.randint(1, 50, (3, 3))    
arr2 = np.random.randint(1, 50, (3, 3))

print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)

print("\nAddition:\n", arr1 + arr2)    # Matrix operations like addition subtraction and division can be simply computed 
print("\nSubtraction:\n", arr1 - arr2)
print("\nElement-wise Multiplication:\n", arr1 * arr2)    # Element wise multiplication is done with a simple *
print("\nDot Product:\n", np.dot(arr1, arr2))    # np.dot gives the dot product of the two arrays

print("\nTranspose of Array 1:\n", arr1.T)    # .T gives the transpose of an array
print("\nTranspose of Array 2:\n", arr2.T)

det1 = np.linalg.det(arr1)    # we take linalg submodule of numpy and use the det function to compute determinant of an array
det2 = np.linalg.det(arr2)

print("\nDeterminant of Array 1:", det1)
print("Determinant of Array 2:", det2)

if det1 != 0:    # If determinant is 0, the inverse of a matrix (adjoint/determinant) cant be computed
    print("\nInverse of Array 1:\n", np.linalg.inv(arr1))    # we take linalg submodule of numpy and use the inv function to compute determinant of an array
else:
    print("\nArray 1 has no inverse.")

if det2 != 0:
    print("\nInverse of Array 2:\n", np.linalg.inv(arr2))
else:
    print("\nArray 2 has no inverse.")

Array 1:
 [[13  3 32]
 [41 33 12]
 [22  3 29]]

Array 2:
 [[48 27 34]
 [ 3  5 48]
 [29 31  5]]

Addition:
 [[61 30 66]
 [44 38 60]
 [51 34 34]]

Subtraction:
 [[-35 -24  -2]
 [ 38  28 -36]
 [ -7 -28  24]]

Element-wise Multiplication:
 [[ 624   81 1088]
 [ 123  165  576]
 [ 638   93  145]]

Dot Product:
 [[1561 1358  746]
 [2415 1644 3038]
 [1906 1508 1037]]

Transpose of Array 1:
 [[13 41 22]
 [ 3 33  3]
 [32 12 29]]

Transpose of Array 2:
 [[48  3 29]
 [27  5 31]
 [34 48  5]]

Determinant of Array 1: -10097.999999999995
Determinant of Array 2: -34812.99999999999

Inverse of Array 1:
 [[-0.09120618 -0.00089127  0.1010101 ]
 [ 0.0916023   0.03238265 -0.11447811]
 [ 0.0597148  -0.0026738  -0.03030303]]

Inverse of Array 2:
 [[ 0.04202453 -0.02639818 -0.03234424]
 [-0.03955419  0.02142878  0.06325223]
 [ 0.00149369  0.02025106 -0.00456726]]
